# Generated by Django 5.2.7 on 2025-12-04 19:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioTecnico',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_usuario_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tecnico', models.CharField(max_length=100)),
                ('correo_tecnico', models.EmailField(max_length=150, unique=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('activo_tecnico', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'db_table': 'usuario_tecnico',
                'ordering': ['nombre_tecnico'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id_sector_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sector', models.CharField(max_length=200)),
                ('activo_sector', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'db_table': 'sector_tecnico',
                'managed': False,
            },
        ),
    ]
