# Generated by Django 5.2.7 on 2025-12-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=100)),
                ('activo_ubicacion', models.BooleanField(default=True)),
                ('id_tipo_sistema', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UbicacionSector',
            fields=[
                ('id_usuario_sector', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField()),
            ],
            options={
                'db_table': 'usuario_sector',
                'managed': False,
            },
        ),
    ]
