# Generated by Django 5.2.7 on 2025-11-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0002_auto_20251117_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id_equipos', models.AutoField(primary_key=True, serialize=False)),
                ('objeto', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('cantidad_por_unidad', models.IntegerField(default=1)),
                ('cantidad_por_cajas', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField()),
                ('activo_equipos', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'equipos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoSistema',
            fields=[
                ('id_tipo_sistema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sistema', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipo_sistema',
                'managed': False,
            },
        ),
    ]
