# Generated by Django 5.2.7 on 2025-12-04 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionDeposito',
            fields=[
                ('id_ubicacion_deposito', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pallet', models.CharField(max_length=100)),
                ('nombre_caja', models.CharField(max_length=100)),
                ('ubicacion_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ubicacion_deposito',
                'managed': False,
            },
        ),
    ]
