# Generated by Django 5.2.7 on 2025-12-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProblema',
            fields=[
                ('id_tipo_problema', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_problema', models.CharField(max_length=200)),
                ('descripcion_problema', models.CharField(blank=True, max_length=200, null=True)),
                ('problema_activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Problema',
                'verbose_name_plural': 'Tipos de Problemas',
                'db_table': 'tipo_problema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_ubicacion', models.CharField(max_length=200)),
                ('activo_ubicacion', models.BooleanField(default=True)),
                ('id_tipo_sistema', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquiposWarehouse',
            fields=[
                ('id_equipos_warehouse', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_equipos_warehouse', models.CharField(max_length=200)),
                ('ip_equipos_warehouse', models.CharField(blank=True, max_length=15, null=True)),
                ('mac_equipos_warehouse', models.CharField(blank=True, max_length=17, null=True)),
                ('serial_equipos_warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('activo_equipos_warehouse', models.BooleanField(default=True)),
                ('ubicacion_warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('firmware_equipos_warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('software_equipos_warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('hardware_equipos_warehouse', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Equipo Warehouse',
                'verbose_name_plural': 'Equipos Warehouse',
                'db_table': 'equipos_warehouse',
            },
        ),
    ]
