# Generated by Django 5.2.7 on 2025-12-17 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparacion_warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionUbicacionWarehouse',
            fields=[
                ('id_asignacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_desasignacion', models.DateTimeField(blank=True, null=True)),
                ('activo_asignacion_equipo_ubicacion', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asignacion_equipo_ubicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SolicitudReparacion',
            fields=[
                ('id_solicitud', models.AutoField(primary_key=True, serialize=False)),
                ('solucion_tecnica', models.TextField(blank=True, help_text='Procedimiento realizado por el laboratorio', null=True)),
                ('th_cantidad', models.FloatField(help_text='Terahash reportado o medido')),
                ('descripcion', models.TextField(help_text='Detalle adicional de la falla')),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('solicitud_activa', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'solicitud_reparacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UbicacionWarehouse',
            fields=[
                ('id_ubicacion_warehouse', models.AutoField(primary_key=True, serialize=False)),
                ('rack', models.CharField(max_length=50)),
                ('fila', models.CharField(max_length=50)),
                ('columna', models.CharField(max_length=50)),
                ('activo_ubicacion_warehouse', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ubicacion_warehouse',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='equiposwarehouse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tipoproblema',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='ubicacion',
            options={'managed': False},
        ),
    ]
